site_name: Project OUROBOROS
theme:
  name: material  # Recommended for better math rendering
  features:
    - navigation.sections
    - navigation.expand
  palette:
    scheme: slate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Electric Propulsion Primer:
      - 1. Introduction:
          - Welcome to OUROBOROS: module-1/welcome.md
          - History of Spaceflight: module-1/history.md
          - Overview of Electric Propulsion: module-1/overview.md
      - 2. Electricity and Magnetism:
          - Single Particle Behavior: module-2/particles.md
          - Fields and Fundamental Laws: module-2/laws.md
          - Applying Laws to Materials: module-2/application.md
      - 3. Plasma Physics:
          - Fundamentals of Plasma: module-3/fundamentals.md
          - Energy Modes & Ionization: module-3/ionization.md
          - Plasma Diffusion: module-3/diffusion.md
          - Plasma Sheaths: module-3/sheaths.md
      - 4. Electrothermal Thrusters:
          - Rocket Propulsion Basics: module-4/rocket-basics.md
          - Resistojets: module-4/resistojets.md
          - Gaseous Discharges: module-4/discharges.md
          - Arcjets: module-4/arcjets.md
      - 5. Electrostatic Thrusters:
          - Ion Engines: module-5/ion-engines.md
          - Hall-Effect Thrusters: module-5/hall-thrusters.md
          - Hollow Cathodes: module-5/cathodes.md