site_name: OUROBOROS Onboarding
theme:
  name: material  # Upgraded to material for better LaTeX styling

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - markdown_include.include:
      base_path: .
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js